package hl7aecg

import (
	"github.com/LIRYC-IHU/hl7v3-aecg/hl7aecg/types"
)

// SetSubject configures the trial subject for this aECG document.
//
// This method uses the complete HL7 aECG structure with ComponentOf > TimepointEvent > SubjectAssignment.
//
// Parameters:
// - id: Subject identifier (e.g., "uuid") <required> if empty, id autogenerated
// - extension: Identifier extension (e.g., "") <optional>
// - role: Subject role code (e.g., ENROLLED || SCREENING) <required>
//
// Example:
// - hl7.SetSubject("SUBJ_001", "", "ENROLLED")
func (h *Hl7xml) SetSubject(id, extension string, code types.CodeRole) *Hl7xml {
	// Initialize ComponentOf structure if nil
	if h.HL7AEcg.ComponentOf == nil {
		h.HL7AEcg.ComponentOf = &types.ComponentOfTimepointEvent{
			TimepointEvent: types.TimepointEvent{
				ComponentOf: types.ComponentOfSubjectAssignment{
					SubjectAssignment: types.SubjectAssignment{
						Subject: types.Subject{
							TrialSubject: types.TrialSubject{},
						},
						ComponentOf: types.ComponentOfClinicalTrial{
							ClinicalTrial: types.ClinicalTrial{},
						},
					},
				},
			},
		}
	}

	// Get reference to TrialSubject in ComponentOf structure
	trialSubject := &h.HL7AEcg.ComponentOf.TimepointEvent.ComponentOf.SubjectAssignment.Subject.TrialSubject

	// Initialize ID if nil
	if trialSubject.ID == nil {
		trialSubject.ID = &types.ID{}
	}

	// Set TrialSubject ID
	trialSubject.ID.SetID(id, extension)

	// Set role code
	if code != "" {
		if trialSubject.Code == nil {
			trialSubject.Code = &types.Code[types.CodeRole, types.CodeSystemOID]{}
		}
		trialSubject.Code.SetCode(code, types.HL7_ResearchSubjectRoleBasis_OID, "")
	}

	return h
}

// SetSubjectDemographics configures optional demographic information for the subject.
//
// All parameters are optional (use empty string to skip).
//
// Parameters:
//   - name: Subject initials (e.g., "BDB")
//   - gender: Gender code (GENDER_MALE, GENDER_FEMALE, GENDER_UNDIFFERENTIATED)
//   - birthDate: Birth date in YYYYMMDD format (e.g., "19530508")
//   - race: Race code (e.g., RACE_WHITE, RACE_ASIAN, etc.)
//
// Example:
//
//	h.SetSubjectDemographics("BDB", types.GENDER_MALE, "19530508", types.RACE_WHITE)
func (h *Hl7xml) SetSubjectDemographics(name string, gender types.GenderCode, birthDate string, race types.RaceCode) *Hl7xml {
	// Ensure ComponentOf structure exists
	if h.HL7AEcg.ComponentOf == nil {
		// Initialize with empty structure - SetSubject should be called first
		h.HL7AEcg.ComponentOf = &types.ComponentOfTimepointEvent{
			TimepointEvent: types.TimepointEvent{
				ComponentOf: types.ComponentOfSubjectAssignment{
					SubjectAssignment: types.SubjectAssignment{
						Subject: types.Subject{
							TrialSubject: types.TrialSubject{},
						},
						ComponentOf: types.ComponentOfClinicalTrial{
							ClinicalTrial: types.ClinicalTrial{},
						},
					},
				},
			},
		}
	}

	// Get reference to TrialSubject
	trialSubject := &h.HL7AEcg.ComponentOf.TimepointEvent.ComponentOf.SubjectAssignment.Subject.TrialSubject

	// Initialize SubjectDemographicPerson if nil
	if trialSubject.SubjectDemographicPerson == nil {
		trialSubject.SubjectDemographicPerson = &types.SubjectDemographicPerson{}
	}

	demo := trialSubject.SubjectDemographicPerson

	if name != "" {
		demo.SetName(name)
	}
	if gender != "" {
		demo.SetGender(gender, "")
	}
	if birthDate != "" {
		demo.SetBirthDate(birthDate)
	}
	if race != "" {
		demo.SetRace(race, "", "")
	}

	return h
}
