package hl7aecg

import (
	"github.com/LIRYC-IHU/hl7v3-aecg/hl7aecg/types"
)

// SetSubject configures the trial subject for this aECG document.
//
// Parameters:
// - id: Subject identifier (e.g., "uuid") <required> if empty, id autogenerated
// - extension: Identifier extension (e.g., "") <optional>
// - role: Subject role code (e.g., ENROLLED || SCREENING) <required>
//
// Example:
// - hl7.SetSubject("SUBJ_001", "", "ENROLLED")
func (h *Hl7xml) SetSubject(id, extension string, code types.CodeRole) *Hl7xml {
	// Initialize Subject if nil
	if h.HL7AEcg.Subject == nil {
		h.HL7AEcg.Subject = &types.TrialSubject{
			ID:   &types.ID{},
			Code: &types.Code[types.CodeRole, types.CodeSystemOID]{},
		}
	}

	// Set TrialSubject ID
	h.HL7AEcg.Subject.ID.SetID(id, extension)

	// Set role code
	if code != "" {
		h.HL7AEcg.Subject.Code.SetCode(code, types.HL7_ResearchSubjectRoleBasis_OID, "")
	}

	return h
}

// SetSubjectDemographics configures optional demographic information for the subject.
//
// All parameters are optional (use empty string to skip).
//
// Parameters:
//   - name: Subject initials (e.g., "BDB")
//   - gender: Gender code (GENDER_MALE, GENDER_FEMALE, GENDER_UNDIFFERENTIATED)
//   - birthDate: Birth date in YYYYMMDD format (e.g., "19530508")
//   - race: Race code (e.g., RACE_WHITE, RACE_ASIAN, etc.)
//
// Example:
//
//	h.SetSubjectDemographics("BDB", types.GENDER_MALE, "19530508", types.RACE_WHITE)
func (h *Hl7xml) SetSubjectDemographics(name string, gender types.GenderCode, birthDate string, race types.RaceCode) *Hl7xml {
	if h.HL7AEcg.Subject == nil {
		h.HL7AEcg.Subject = &types.TrialSubject{}
	}

	if h.HL7AEcg.Subject.SubjectDemographicPerson == nil {
		h.HL7AEcg.Subject.SubjectDemographicPerson = &types.SubjectDemographicPerson{}
	}

	demo := h.HL7AEcg.Subject.SubjectDemographicPerson

	if name != "" {
		demo.SetName(name)
	}
	if gender != "" {
		demo.SetGender(gender, "")
	}
	if birthDate != "" {
		demo.SetBirthDate(birthDate)
	}
	if race != "" {
		demo.SetRace(race, "", "")
	}

	return h
}
