package types

// SetSeriesCode sets or updates the series code with all attributes.
//
// This method allows updating the series code that is generated by default
// to include additional attributes like codeSystemName and displayName.
//
// Parameters:
//   - code: The code value (e.g., "RHYTHM", "REPRESENTATIVE_BEAT")
//   - codeSystem: The OID of the code system (e.g., "2.16.840.1.113883.5.4")
//   - codeSystemName: Human-readable name of the code system (e.g., "ActCode")
//   - displayName: Human-readable name of the code (e.g., "Rhythm Waveforms")
//
// Example:
//
//	series.SetSeriesCode(
//	    RHYTHM_CODE,
//	    HL7_ActCode_OID,
//	    "ActCode",
//	    "Rhythm Waveforms",
//	)
//
// XML Output:
//
//	<code code="RHYTHM"
//	      codeSystem="2.16.840.1.113883.5.4"
//	      codeSystemName="ActCode"
//	      displayName="Rhythm Waveforms"/>
//
// Returns the Series pointer for method chaining.
func (s *Series) SetSeriesCode(code SeriesTypeCode, codeSystem CodeSystemOID, codeSystemName, displayName string) *Series {
	s.Code = &Code[SeriesTypeCode, CodeSystemOID]{
		Code:           code,
		CodeSystem:     codeSystem,
		CodeSystemName: codeSystemName,
		DisplayName:    displayName,
	}
	return s
}
