package types

// SetSeriesCode sets or updates the series code with all attributes.
//
// This method allows updating the series code that is generated by default
// to include additional attributes like codeSystemName and displayName.
//
// Parameters:
//   - code: The code value (e.g., "RHYTHM", "REPRESENTATIVE_BEAT")
//   - codeSystem: The OID of the code system (e.g., "2.16.840.1.113883.5.4")
//   - codeSystemName: Human-readable name of the code system (e.g., "ActCode")
//   - displayName: Human-readable name of the code (e.g., "Rhythm Waveforms")
//
// Example:
//
//	series.SetSeriesCode(
//	    RHYTHM_CODE,
//	    HL7_ActCode_OID,
//	    "ActCode",
//	    "Rhythm Waveforms",
//	)
//
// XML Output:
//
//	<code code="RHYTHM"
//	      codeSystem="2.16.840.1.113883.5.4"
//	      codeSystemName="ActCode"
//	      displayName="Rhythm Waveforms"/>
//
// Returns the Series pointer for method chaining.
func (s *Series) SetSeriesCode(code SeriesTypeCode, codeSystem CodeSystemOID, codeSystemName, displayName string) *Series {
	s.Code = &Code[SeriesTypeCode, CodeSystemOID]{
		Code:           code,
		CodeSystem:     codeSystem,
		CodeSystemName: codeSystemName,
		DisplayName:    displayName,
	}
	return s
}

// SetDerivedSeriesCode sets the code for the most recently added derived series.
//
// This method updates the series code of the last derived series added to this series.
//
// Parameters:
//   - code: The code value (e.g., "REPRESENTATIVE_BEAT", "MEDIAN_BEAT")
//   - codeSystem: The OID of the code system
//   - codeSystemName: Human-readable name of the code system
//   - displayName: Human-readable name of the code
//
// Returns the Series pointer for method chaining.
func (s *Series) SetDerivedSeriesCode(
	code SeriesTypeCode,
	codeSystem CodeSystemOID,
	codeSystemName, displayName string,
) *Series {
	if len(s.Derivation) == 0 {
		return s
	}
	lastDerived := &s.Derivation[len(s.Derivation)-1].DerivedSeries
	lastDerived.Code.SetCode(code, codeSystem, codeSystemName, displayName)
	return s
}

// SetDerivedSeriesID sets the ID for the most recently added derived series.
//
// This method updates the ID of the last derived series added to this series.
//
// Parameters:
//   - root: OID root (can be empty to inherit from document)
//   - extension: Extension identifier (e.g., "derivedSeries", "representativeBeat1")
//
// Returns the Series pointer for method chaining.
func (s *Series) SetDerivedSeriesID(root, extension string) *Series {
	if len(s.Derivation) == 0 {
		return s
	}
	lastDerived := &s.Derivation[len(s.Derivation)-1].DerivedSeries
	if lastDerived.ID == nil {
		lastDerived.ID = &ID{}
	}
	lastDerived.ID.SetID(root, extension)
	return s
}
