// Package hl7aecg provides types and parsers for HL7 aECG (Annotated ECG) files.
//
// The HL7 aECG standard (ANSI, January 2004) defines an XML format for exchanging
// electrocardiogram waveforms and annotations in clinical trials. This package
// implements the data structures necessary to parse and manipulate aECG files
// according to FDA requirements.
// Standard Reference: HL7 aECG Implementation Guide (Final 21-March-2005)
// OID: 2.16.840.1.113883.6.24 (MDC - Medical Device Communications)
//
// Example XML Structure:
//
//	<AnnotatedECG xmlns="urn:hl7-org:v3">
//	  <id root="728989ec-b8bc-49cd-9a5a-30be5ade1db5"/>
//	  <code code="93000" codeSystem="2.16.840.1.113883.6.12"/>
//	  <text>Annotated ECG for FDA Review</text>
//	  <effectiveTime>
//	    <low value="20020510092700"/>
//	    <high value="20020510092900"/>
//	  </effectiveTime>
//	  <confidentialityCode code="B" codeSystem="" displayName="Blinded to Sponsor and Investigator"/>
//	  <reasonCode code="PER_PROTOCOL" codeSystem=""/>
//	</AnnotatedECG>
package types

import (
	"encoding/xml"
)

type ProcedureCode string

// HL7AEcg represents the root element of an HL7 aECG XML document.
//
// This structure contains the top-level metadata for an annotated ECG, including
// identifiers, codes, timing information, and confidentiality settings. It corresponds
// to the <AnnotatedECG> XML element in the HL7 aECG schema.
type HL7AEcg struct {
	XMLName xml.Name `xml:"AnnotatedECG"`

	// Attribute to specify XML Schema Instance namespace.
	Xmlns    string `xml:"xmlns,attr"`
	XmlnsVoc string `xml:"xmlns:voc,attr"`
	XmlnsXsi string `xml:"xmlns:xsi,attr"`

	// Type specifies the HL7 v3 RIM class type for this clinical document.
	// Required for XML schema validation against PORT_MT020001.xsd.
	// Always set to "Observation" per HL7 v3 RIM specification.
	Type string `xml:"type,attr"`

	// SchemaLocation specifies the path to the HL7 aECG XML schema file.
	// Required for XML schema validation. Uses xsi namespace prefix.
	// Default: "urn:hl7-org:v3 ../schema/PORT_MT020001.xsd"
	SchemaLocation string `xml:"xsi:schemaLocation,attr"`

	// ID is the unique identifier for this aECG document.
	// Must be globally unique using UUID.
	//
	// UUID Format: "728989ec-b8bc-49cd-9a5a-30be5ade1db5"
	//   - 32 hexadecimal digits with 4 hyphens (8-4-4-4-12 format)
	//   - Generated by ECG device or management system
	ID *ID `xml:"id"`

	// Code identifies the type of clinical document or procedure.
	//
	// Common Code Systems:
	//   1. CPT (Current Procedural Terminology) - OID: 2.16.840.1.113883.6.12
	//      Example: code="93000" (Complete 12-lead ECG)
	//
	//   2. HL7 ActCode - OID: 2.16.840.1.113883.5.4
	//      Example: code="RHYTHM" (ECG rhythm waveforms)
	//      Example: code="REPRESENTATIVE_BEAT" (Representative beat waveforms)
	//
	// Real Example from FDA submission:
	//   code="93000" codeSystem="2.16.840.1.113883.6.12"
	//   This is CPT code for "Electrocardiogram, routine ECG with at least 12 leads"
	Code *Code[CPT_CODE, CodeSystemOID] `xml:"code"`

	// Text provides a human-readable narrative description of the ECG.
	// This field is optional but commonly used for clinical context.
	//
	// Common Uses:
	//   - Study context: "Annotated ECG for FDA Review"
	//   - Visit information: "12-lead ECG acquired during baseline visit"
	//   - Clinical notes: "ECG with evidence of left ventricular hypertrophy"
	//
	// Real Example: "Annotated ECG for FDA Review"
	Text string `xml:"text,omitempty"`

	// EffectiveTime specifies the time interval during which the ECG was acquired.
	// The Low value indicates the start of acquisition, and High indicates the end.
	//
	// Format: HL7 TS (Timestamp)
	//   - YYYYMMDDHHmmss (without milliseconds)
	//   - YYYYMMDDHHmmss.SSS (with milliseconds)
	//
	// Real Example:
	//   Low:  "20020510092700" = May 10, 2002 at 09:27:00
	//   High: "20020510092900" = May 10, 2002 at 09:29:00
	//   Duration: 2 minutes of ECG data
	//
	// Typical Durations:
	//   - Standard 12-lead: 10 seconds
	//   - Holter monitoring: 24 hours
	//   - Exercise stress test: 5-15 minutes
	EffectiveTime *EffectiveTime `xml:"effectiveTime"`

	// ConfidentialityCode indicates the confidentiality level of the ECG data.
	// Used in clinical trials to specify blinding requirements.
	//
	// Standard Codes (from CDISC, not formally defined by HL7):
	//   - "S": Blinded to sponsor only
	//   - "I": Blinded to investigator only
	//   - "B": Blinded to both sponsor and investigator (double-blind)
	//   - "C": Custom blinding arrangement
	//
	// Real Example:
	//   code="B"
	//   displayName="Blinded to Sponsor and Investigator"
	//   codeSystem="" (empty because not formally defined)
	//
	// Note: In clinical trials, blinding ensures unbiased ECG interpretation.
	// The sponsor and/or investigator should not know treatment assignments.
	ConfidentialityCode *Code[ConfidentialityCode, string] `xml:"confidentialityCode,omitempty"`

	// ReasonCode specifies why the ECG was acquired in relation to the study protocol.
	//
	// Suggested Codes (not formally defined by HL7):
	//   - "PER_PROTOCOL": Scheduled acquisition per study protocol
	//   - "NOT_IN_PROTOCOL": Unscheduled acquisition (e.g., adverse event)
	//   - "IN_PROTOCOL_WRONG_EVENT": Acquired at incorrect timepoint
	//
	// Real Example:
	//   code="PER_PROTOCOL"
	//   codeSystem="" (empty because not formally defined)
	//
	// This helps FDA reviewers understand if the ECG was part of the planned
	// study procedures or was acquired for other clinical reasons.
	ReasonCode *Code[ReasonCode, string] `xml:"reasonCode,omitempty"`

	// ComponentOf links this AnnotatedECG to a TimepointEvent (visit/study event).
	//
	// This is the complete HL7 aECG structure that includes timepoint event information
	// and nests the subject and clinical trial within the componentOf hierarchy.
	//
	// When using ComponentOf, the Subject and ClinicalTrial should be nested within
	// the TimepointEvent > SubjectAssignment structure instead of being direct children.
	//
	// XML Structure:
	//   <componentOf>
	//     <timepointEvent>
	//       <componentOf>
	//         <subjectAssignment>
	//           <subject>...</subject>
	//           <componentOf>
	//             <clinicalTrial>...</clinicalTrial>
	//           </componentOf>
	//         </subjectAssignment>
	//       </componentOf>
	//     </timepointEvent>
	//   </componentOf>
	//
	// XML Tag: <componentOf>...</componentOf>
	// Cardinality: Optional (alternative to direct Subject/ClinicalTrial)
	ComponentOf *ComponentOfTimepointEvent `xml:"componentOf,omitempty"`

	// ClinicalTrial Protocol references the protocol defining the clinical trial.
	//
	// Note: Can be provided either as a direct child OR nested within ComponentOf.
	// If using ComponentOf structure, this field should be omitted.
	//
	// required: Yes (when not using ComponentOf structure)
	ClinicalTrial *ClinicalTrial `xml:"clinicalTrial,omitempty"`

	// Subject identifies the trial subject from which the ECG was obtained.
	//
	// id
	// Required: The unique identifier for the subject. Composed of a root and optional extension.
	// The root must be included, and is a UID. The optional extension may be anything. The
	// combination of the root and extension must be universally unique.
	// It is highly recommended at that sponsor (or its vendor) assign a unique OID to every
	// subject. This OID will go into the root part of the ID. The traditional identifier will go into the
	// extension.
	// Code
	// Optional: The role the subject was in at the time of the ECG waveform collection. As of this
	// guide's publishing, HL7 had defined a vocabulary for this called
	// "ResearchSubjectRoleBasis", UID=" 2.16.840.1.113883.5.111", but does not have any
	// defined codes within it. Suggested values are:
	// • SCREENING – the subject was being screened for participation in the trial but had
	// not yet been enrolled.
	// • ENROLLED – the subject was enrolled in the trial.
	//
	// Note: Can be provided either as a direct child OR nested within ComponentOf.
	// If using ComponentOf structure, this field should be omitted.
	//
	// required: Yes (when not using ComponentOf structure)
	Subject *TrialSubject `xml:"subject,omitempty"`

	// Component contains the ECG waveform series and annotations.
	//
	// Although technically optional in the schema, an aECG without at least
	// one series containing waveforms is not useful.
	//
	// Typically contains 1 or more Series:
	//   - RHYTHM series: Raw ECG waveforms from device
	//   - REPRESENTATIVE_BEAT series: Derived representative beats
	//
	// XML Tag: <component>...</component>
	// Cardinality: Optional but strongly recommended (0..*)
	Component []Component `xml:"component,omitempty"`
}

// NewHL7AEcg creates a new HL7AEcg instance with a unique ID if none is provided.
// If id is empty, a new UUID will be generated for the Root.
// The extension is optional.
func (e *HL7AEcg) NewHL7AEcg(id, extension, text string) *HL7AEcg {
	return &HL7AEcg{}
}

// ID represents an HL7 Instance Identifier (II datatype).
//
// IDs in HL7 consist of a root (required) and an optional extension.
// The root must be a globally unique identifier (UUID).
//
// Two Common Formats:
//
//  1. UUID (Universally Unique Identifier):
//     Format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
//     Example: "728989ec-b8bc-49cd-9a5a-30be5ade1db5"
//     Usage: Generated automatically by ECG devices or systems
//
// Real Example from FDA submission:
//
//	<id root="728989ec-b8bc-49cd-9a5a-30be5ade1db5"/>
//	(UUID format, no extension needed)
//
// XML Mapping:
//
//	<id root="728989ec-b8bc-49cd-9a5a-30be5ade1db5"/>
type ID struct {
	// Root is the UUID that ensures global uniqueness.
	//
	// UUID Example: "728989ec-b8bc-49cd-9a5a-30be5ade1db5"
	//   - 32 hexadecimal characters with hyphens
	//   - Generated by uuid.New() or similar
	//   - No extension needed when using UUID
	//
	// Required: Yes
	Root string `xml:"root,attr"`

	// Extension is an optional identifier unique within the context of Root.
	// Only used when Root is an OID (not needed for UUIDs).
	//
	// Examples:
	//   - "ECG-001" (ECG serial number)
	//   - "SUBJECT-12345" (Subject ID)
	//   - "SITE01-001" (Site + sequence number)
	//
	// Not present in UUID-based IDs:
	//   <id root="728989ec-b8bc-49cd-9a5a-30be5ade1db5"/> (no extension)
	//
	// Required: No (omitted in XML when empty)
	Extension string `xml:"extension,attr,omitempty"`
}

// Code represents an HL7 Coded Value (CE datatype - Coded Element).
//
// Codes consist of three main components:
//  1. Code: The actual code value
//  2. CodeSystem: OID identifying the vocabulary
//  3. DisplayName: Human-readable name (optional)
//
// Real-World Examples:
//
//  1. CPT Code (from FDA example):
//     <code code="93000" codeSystem="2.16.840.1.113883.6.12"/>
//     Meaning: "Electrocardiogram, routine ECG with at least 12 leads"
//
//  2. Confidentiality Code (CDISC):
//     <confidentialityCode code="B" codeSystem="" displayName="Blinded to Sponsor and Investigator"/>
//     Note: Empty codeSystem because not formally defined by HL7
//
//  3. ECG Lead (MDC):
//     <code code="MDC_ECG_LEAD_I" codeSystem="2.16.840.1.113883.6.24" displayName="Lead I"/>
//
// Common Code Systems (OIDs):
//   - 2.16.840.1.113883.6.12: CPT (Current Procedural Terminology)
//   - 2.16.840.1.113883.5.4: HL7 ActCode (RHYTHM, REPRESENTATIVE_BEAT)
//   - 2.16.840.1.113883.6.24: ISO 11073 MDC (ECG leads, annotations)
//   - 2.16.840.1.113883.6.1: LOINC (clinical observations)
type Code[T ~string, U ~string] struct {
	// Code is the actual code value from the specified vocabulary.
	//
	// Examples from real aECG files:
	//   - "93000" (CPT code for complete ECG)
	//   - "RHYTHM" (HL7 ActCode for rhythm series)
	//   - "MDC_ECG_LEAD_I" (MDC code for Lead I)
	//   - "B" (CDISC code for double-blind)
	//   - "PER_PROTOCOL" (suggested code for protocol compliance)
	//
	// Required: Yes
	Code T `xml:"code,attr"`

	// CodeSystem is the OID identifying the vocabulary that defines the Code.
	//
	// Common Values:
	//   - "2.16.840.1.113883.6.12": CPT codes
	//   - "2.16.840.1.113883.5.4": HL7 ActCode
	//   - "2.16.840.1.113883.6.24": ISO 11073 MDC
	//
	// Special Case: Empty String
	//   Some codes (like ConfidentialityCode and ReasonCode) use empty
	//   codeSystem="" because they are suggested values not formally
	//   defined by HL7 or other standards bodies.
	//
	// Real Example: codeSystem="2.16.840.1.113883.6.12" (CPT)
	// Real Example: codeSystem="" (for CDISC suggested values)
	//
	// Required: Yes (but may be empty string for informal vocabularies)
	CodeSystem U `xml:"codeSystem,attr"`

	// CodeSystemName is an optional human-readable name for the code system.
	//
	// Examples:
	//   - "MDC" (for ISO 11073)
	//   - "ActCode" (for HL7 ActCode)
	//   - "CPT" (for Current Procedural Terminology)
	//
	// Not present in the FDA example, but useful for documentation.
	//
	// Required: No (omitted in XML when empty)
	CodeSystemName string `xml:"codeSystemName,attr,omitempty"`

	// DisplayName is a human-readable name for the code.
	// Used for display purposes, not for processing logic.
	//
	// Examples:
	//   - "Blinded to Sponsor and Investigator" (for code "B")
	//   - "Lead I" (for code "MDC_ECG_LEAD_I")
	//   - "ECG Rhythm Waveforms" (for code "RHYTHM")
	//
	// Real Example: displayName="Blinded to Sponsor and Investigator"
	//
	// Required: No (omitted in XML when empty)
	DisplayName string `xml:"displayName,attr,omitempty"`
}

// NewConfidentialityCode creates a new confidentiality code instance.
func NewCode[T ~string, U ~string](code T, codeSystem U, codeSystemName string, displayName string) *Code[T, U] {
	return &Code[T, U]{
		Code:           code,
		CodeSystem:     codeSystem,
		CodeSystemName: codeSystemName,
		DisplayName:    displayName,
	}
}

// EffectiveTime represents an HL7 interval of time (IVL<TS> datatype).
//
// Used to specify when an ECG was acquired. The interval is inclusive
// of both Low and High boundaries.
//
// Real-World Example from FDA submission:
//
//	<effectiveTime>
//	  <low value="20020510092700"/>   <!-- May 10, 2002 09:27:00 -->
//	  <high value="20020510092900"/>  <!-- May 10, 2002 09:29:00 -->
//	</effectiveTime>
//
// This represents a 2-minute ECG acquisition window.
//
// HL7 Timestamp Format (TS):
//
//	Basic: YYYYMMDDHHmmss
//	  - "20020510092700" = May 10, 2002 at 09:27:00
//
//	With Milliseconds: YYYYMMDDHHmmss.SSS
//	  - "20020510092700.000" = May 10, 2002 at 09:27:00.000
//
//	Variable Precision (less common):
//	  - "2002" (year only)
//	  - "202005" (year and month)
//	  - "20020510" (date only)
//
// Common Use Cases:
//   - Standard 12-lead ECG: 10-second window
//   - Holter monitor: 24-hour window
//   - Exercise stress test: 5-15 minute window
//   - Continuous monitoring: Hours to days
type EffectiveTime struct {
	// Low is the start of the time interval (inclusive).
	// Represents when ECG acquisition began.
	//
	// Format: YYYYMMDDHHmmss or YYYYMMDDHHmmss.SSS
	//
	// Real Example: "20020510092700"
	//   Decoded: May 10, 2002 at 09:27:00 (9:27 AM)
	//   - 2002: Year
	//   - 05: May (month 05)
	//   - 10: Day 10
	//   - 09: Hour 09 (9 AM)
	//   - 27: Minute 27
	//   - 00: Second 00
	//
	// Required: Yes (for most aECG use cases)
	Low Time `xml:"low"`

	// High is the end of the time interval (inclusive).
	// Represents when ECG acquisition completed.
	//
	// Format: YYYYMMDDHHmmss or YYYYMMDDHHmmss.SSS
	//
	// Real Example: "20020510092900"
	//   Decoded: May 10, 2002 at 09:29:00 (9:29 AM)
	//   Duration from Low: 2 minutes
	//
	// Note: Some ECG devices only record Low (start time).
	// High may be calculated as Low + duration, or omitted entirely.
	//
	// Required: Recommended (may be omitted by some devices)
	High Time `xml:"high"`
}

func NewEffectiveTime(low, high string, low_inclusive, high_inclusive *bool) *EffectiveTime {
	t := &EffectiveTime{
		Low:  Time{Value: low},
		High: Time{Value: high},
	}
	if low_inclusive != nil {
		t.Low.Inclusive = low_inclusive
	}
	if high_inclusive != nil {
		t.High.Inclusive = high_inclusive
	}
	return t
}

// Time represents an HL7 Timestamp (TS datatype).
type Time struct {
	Value     string `xml:"value,attr"`
	Inclusive *bool  `xml:"inclusive,attr,omitempty"`
}

// ComponentOfTimepointEvent links the AnnotatedECG to a TimepointEvent.
//
// This structure enables the complete HL7 aECG format where subject and
// clinical trial information is nested within a timepoint event context.
//
// XML Structure:
//
//	<componentOf>
//	  <timepointEvent>...</timepointEvent>
//	</componentOf>
//
// Cardinality: Optional (within AnnotatedECG)
// Reference: HL7 aECG Implementation Guide, Page 17-18
type ComponentOfTimepointEvent struct {
	// TimepointEvent represents the visit or study event during which the ECG was acquired.
	//
	// XML Tag: <timepointEvent>...</timepointEvent>
	// Cardinality: Required (within ComponentOf)
	TimepointEvent TimepointEvent `xml:"timepointEvent"`
}
